### Para el punto 1
@baseURL = http://localhost:3003
@contentType = application/json

### Obtener todos los productos
GET {{baseURL}}/api/productos
Content-Type: {{contentType}}

###

### Verificar que server funcione
GET {{baseURL}}/
Content-Type: {{contentType}}

###